"""create_tasks_and_daily_retro

Revision ID: 853846726201
Revises: 004
Create Date: 2026-06-23 02:04:38.449580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '853846726201'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.alter_column('achievements', 'category',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('STREAK', 'MILESTONE', 'CONSISTENCY', 'MASTERY', 'SOCIAL', 'HEALTH', 'RESEARCH', 'IELTS', name='achievementcategory', native_enum=False),
               existing_nullable=False)
    op.add_column('daily_snapshots', sa.Column('day_target', sa.Text(), nullable=True))
    op.add_column('daily_snapshots', sa.Column('achieved_summary', sa.Text(), nullable=True))
    op.add_column('daily_snapshots', sa.Column('positives', sa.Text(), nullable=True))
    op.add_column('daily_snapshots', sa.Column('negatives', sa.Text(), nullable=True))
    op.add_column('daily_snapshots', sa.Column('tomorrow_plan', sa.Text(), nullable=True))
    op.drop_index('ix_day_events_date', table_name='day_events')
    op.create_index(op.f('ix_day_events_event_date'), 'day_events', ['event_date'], unique=False)
    op.alter_column('goals', 'timeframe',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ANNUAL', 'QUARTERLY', 'MONTHLY', 'WEEKLY', 'DAILY', name='goaltimeframe', native_enum=False),
               existing_nullable=False)
    op.alter_column('goals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('goals', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='goalpriority', native_enum=False),
               existing_nullable=False)
    op.alter_column('habits', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('STUDY', 'HEALTH', 'SOCIAL', 'CAREER', 'PERSONAL', 'IELTS', 'AI_ENGINEERING', 'CS_FOUNDATIONS', 'RESEARCH', 'SPORTS', name='habitcategory', native_enum=False),
               existing_nullable=False)
    op.alter_column('habits', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='habitfrequency', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_ielts_mock_tests_profile_id'), 'ielts_mock_tests', ['profile_id'], unique=False)
    op.create_index(op.f('ix_ielts_mock_tests_user_id'), 'ielts_mock_tests', ['user_id'], unique=False)
    op.alter_column('ielts_study_sessions', 'skill',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('READING', 'LISTENING', 'WRITING', 'SPEAKING', 'VOCABULARY', 'GRAMMAR', name='ieltsskill', native_enum=False),
               existing_nullable=False)
    op.alter_column('knowledge_notes', 'note_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('LEARNING', 'RESEARCH_FINDING', 'IDEA', 'BOOK_SUMMARY', 'ARTICLE_DRAFT', 'REFERENCE', 'LESSON_LEARNED', 'PROJECT_NOTE', 'REFLECTION', 'OTHER', name='notetype', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_mastery_study_sessions_skill_area_id'), 'mastery_study_sessions', ['skill_area_id'], unique=False)
    op.create_index(op.f('ix_mastery_study_sessions_user_id'), 'mastery_study_sessions', ['user_id'], unique=False)
    op.drop_constraint('uq_namaz_user_date', 'namaz_logs', type_='unique')
    op.add_column('pomodoro_sessions', sa.Column('task_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'pomodoro_sessions', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_research_papers_user_id'), 'research_papers', ['user_id'], unique=False)
    op.create_index(op.f('ix_research_projects_user_id'), 'research_projects', ['user_id'], unique=False)
    op.alter_column('skill_areas', 'domain',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('AI_ENGINEERING', 'CS_FOUNDATIONS', name='masterydomain', native_enum=False),
               existing_nullable=False)
    op.alter_column('skill_areas', 'proficiency',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_skill_topics_skill_area_id'), 'skill_topics', ['skill_area_id'], unique=False)
    op.alter_column('social_interactions', 'interaction_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('FRIEND_MEETUP', 'FAMILY', 'PROFESSIONAL_NETWORKING', 'ONLINE_COMMUNITY', 'EVENT', 'MENTORING', 'COLLABORATION', 'CASUAL_CHAT', name='interactiontype', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_sports_activities_user_id'), 'sports_activities', ['user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_vocabulary_entries_profile_id'), 'vocabulary_entries', ['profile_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_entries_user_id'), 'vocabulary_entries', ['user_id'], unique=False)
    op.alter_column('workout_sessions', 'workout_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('GYM', 'RUNNING', 'WALKING', 'SPORTS', 'MOBILITY', 'CYCLING', 'SWIMMING', 'OTHER', name='workouttype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'workout_type',
               existing_type=sa.Enum('GYM', 'RUNNING', 'WALKING', 'SPORTS', 'MOBILITY', 'CYCLING', 'SWIMMING', 'OTHER', name='workouttype', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_vocabulary_entries_user_id'), table_name='vocabulary_entries')
    op.drop_index(op.f('ix_vocabulary_entries_profile_id'), table_name='vocabulary_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_sports_activities_user_id'), table_name='sports_activities')
    op.alter_column('social_interactions', 'interaction_type',
               existing_type=sa.Enum('FRIEND_MEETUP', 'FAMILY', 'PROFESSIONAL_NETWORKING', 'ONLINE_COMMUNITY', 'EVENT', 'MENTORING', 'COLLABORATION', 'CASUAL_CHAT', name='interactiontype', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_skill_topics_skill_area_id'), table_name='skill_topics')
    op.alter_column('skill_areas', 'proficiency',
               existing_type=sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('skill_areas', 'domain',
               existing_type=sa.Enum('AI_ENGINEERING', 'CS_FOUNDATIONS', name='masterydomain', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_research_projects_user_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_papers_user_id'), table_name='research_papers')
    op.drop_constraint(None, 'pomodoro_sessions', type_='foreignkey')
    op.drop_column('pomodoro_sessions', 'task_id')
    op.create_unique_constraint('uq_namaz_user_date', 'namaz_logs', ['user_id', 'log_date'])
    op.drop_index(op.f('ix_mastery_study_sessions_user_id'), table_name='mastery_study_sessions')
    op.drop_index(op.f('ix_mastery_study_sessions_skill_area_id'), table_name='mastery_study_sessions')
    op.alter_column('knowledge_notes', 'note_type',
               existing_type=sa.Enum('LEARNING', 'RESEARCH_FINDING', 'IDEA', 'BOOK_SUMMARY', 'ARTICLE_DRAFT', 'REFERENCE', 'LESSON_LEARNED', 'PROJECT_NOTE', 'REFLECTION', 'OTHER', name='notetype', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('ielts_study_sessions', 'skill',
               existing_type=sa.Enum('READING', 'LISTENING', 'WRITING', 'SPEAKING', 'VOCABULARY', 'GRAMMAR', name='ieltsskill', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_ielts_mock_tests_user_id'), table_name='ielts_mock_tests')
    op.drop_index(op.f('ix_ielts_mock_tests_profile_id'), table_name='ielts_mock_tests')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.alter_column('habits', 'frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='habitfrequency', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('habits', 'category',
               existing_type=sa.Enum('STUDY', 'HEALTH', 'SOCIAL', 'CAREER', 'PERSONAL', 'IELTS', 'AI_ENGINEERING', 'CS_FOUNDATIONS', 'RESEARCH', 'SPORTS', name='habitcategory', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('goals', 'priority',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='goalpriority', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('goals', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('goals', 'timeframe',
               existing_type=sa.Enum('ANNUAL', 'QUARTERLY', 'MONTHLY', 'WEEKLY', 'DAILY', name='goaltimeframe', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_day_events_event_date'), table_name='day_events')
    op.create_index('ix_day_events_date', 'day_events', ['event_date'], unique=False)
    op.drop_column('daily_snapshots', 'tomorrow_plan')
    op.drop_column('daily_snapshots', 'negatives')
    op.drop_column('daily_snapshots', 'positives')
    op.drop_column('daily_snapshots', 'achieved_summary')
    op.drop_column('daily_snapshots', 'day_target')
    op.alter_column('achievements', 'category',
               existing_type=sa.Enum('STREAK', 'MILESTONE', 'CONSISTENCY', 'MASTERY', 'SOCIAL', 'HEALTH', 'RESEARCH', 'IELTS', name='achievementcategory', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
